### ISSUE TITLE
Access body of error responses

### ISSUE THREAD

**Issue by Karlinde** [ruma/ruma-client#32]
The server will sometimes return HTTP 4XX with a body containing futher details on what caused the error, as described in https://matrix.org/docs/spec/client_server/r0.6.0#api-standards

When implementing a client, you need to get access to the fields in the body in order to know how to handle the error properly. For example in the username availability endpoint: https://matrix.org/docs/spec/client_server/r0.6.0#get-matrix-client-r0-register-available

This also comes into play when using the [user-interactive authentication api](https://matrix.org/docs/spec/client_server/r0.6.0#user-interactive-authentication-api) where the whole process seems to be built on reading the body of HTTP 401 responses.

I don't know if this is best handled here on the client library level or if it should be made more general, perhaps even when generating the response types in the ruma_api macro.

**Comment by jplatte** [comment]
This is best handled in ruma-client IMO, thanks for opening an issue. It was on my mind already since somebody (can't remember who, was it you?) mentioned it recently on matrix, but it's good to have an issue for it here nevertheless.

**Comment by jplatte** [comment]
I was wrong, this doesn't have to be handled in ruma-client. Accessing the body of error responses is possible with ruma-api master since https://github.com/ruma/ruma-api/commit/542bef8c4ac338aae51fbb0f625f2ae254fb71b5.

There's still more things to do re. providing all potentially interesting information in case something went wrong (e.g. https://github.com/ruma/ruma-api/issues/37), but this specific issue is now fixed.
